# Site settings
title: y0ga
#email: bugurtbor1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Артюша - черт!
baseurl: "/freezing-tribble" # the subpath of your site, e.g. /blog/
url: "http://y0ga.github.io/freezing-tribble/" # the base hostname & protocol for your site
twitter_username: nix_vick
#github_username:  y0ga

# Build settings
markdown: kramdown
